# Generated by Django 6.0 on 2026-01-08 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('tab_number', models.CharField(db_column='Таб. №', max_length=20, primary_key=True, serialize=False, verbose_name='Таб. №')),
                ('full_name', models.CharField(blank=True, db_column='Ф.И.О.', max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, db_column='Должность /профессия (разряд, категория)', max_length=200, verbose_name='Должность')),
                ('recommendation', models.TextField(blank=True, db_column='Рекомендации к повышению оплаты', verbose_name='Рекомендация')),
                ('increase', models.FloatField(blank=True, db_column='Повышение оплаты', null=True, verbose_name='Повышение')),
                ('fot', models.FloatField(blank=True, db_column='ФОТ', null=True, verbose_name='ФОТ')),
            ],
            options={
                'db_table': 'peoples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_number', models.CharField(max_length=20, unique=True, verbose_name='Таб. №')),
                ('is_budgetolog', models.BooleanField(default=False, verbose_name='Бюджетолог')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
